from pptx import Presentation


def create_ppt(slides_data, output_path):

    prs = Presentation()

    # Title Slide
    slide = prs.slides.add_slide(
        prs.slide_layouts[0]
    )

    slide.shapes.title.text = slides_data["title"]

    slide.placeholders[1].text = "Generated by PPT LLM"

    # Content Slides
    for slide_data in slides_data["slides"]:

        slide = prs.slides.add_slide(
            prs.slide_layouts[1]
        )

        slide.shapes.title.text = slide_data["title"]

        content = slide.placeholders[1]

        content.text = "\n".join(
            slide_data["bullets"]
        )

    prs.save(output_path)

    return output_path